spring.application.name=applytabai-api
spring.config.import=optional:file:.env[.properties]
server.port=${SPRING_BOOT_PORT:8080}
spring.docker.compose.enabled=${SPRING_DOCKER_COMPOSE_ENABLED:false}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:${POSTGRES_PORT:5432}/mydb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.open-in-view=false
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
management.endpoints.web.exposure.include=health,info
